# Generated by Django 3.2.5 on 2021-07-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('average_rating', models.FloatField()),
                ('num_votes', models.IntegerField()),
                ('genres', models.CharField(max_length=50)),
                ('runtime_minutes', models.IntegerField()),
            ],
        ),
    ]
